version: '3.3'

services:

  api-service:
    container_name: api-service
    build:
      context: ./api-service
      dockerfile: Dockerfile-dev
    volumes:
      - './api-service:/usr/src/app'
    ports:
      - 5001:5000
